spring.application.name=EmployeePayrollApp

# Server
server.port=8080

# PostgreSQL Database
spring.datasource.url=jdbc:postgresql://localhost:5432/payrolldb
spring.datasource.username=postgres
spring.datasource.password=246863
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Logging

# Root level: INFO (don't set too low globally)
logging.level.root=INFO
logging.level.com.example.demo=DEBUG

# Your app layers: DEBUG for controllers/services (unlocks trace/debug)
logging.level.com.yourpackage.controller=DEBUG
logging.level.com.yourpackage.service=DEBUG
logging.level.com.yourpackage.repository=DEBUG

# PostgreSQL/Hibernate: Full SQL + params tracing
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.springframework.jdbc=DEBUG

# Spring Web: API request/response details
logging.level.org.springframework.web=DEBUG


# Disable noisy libs
logging.level.org.springframework.boot.autoconfigure=ERROR

# Validation errors
logging.level.org.springframework.validation=DEBUG 

# Request detail
logging.level.org.springframework.web.servlet.mvc.method.annotation=DEBUG  
